---
- name: Install tzdata on Ubuntu if needed
  apt:
    name: ["tzdata"]
    update_cache: yes
  when:
    - ansible_distribution == 'Ubuntu'

- name: Set timezone variables
  copy: 
    content: "{{ timezone if timezone is defined else 'Etc/UTC' }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"
  notify_now:
    - update timezone
  when:
    - ansible_distribution == 'Ubuntu'
